### ISSUE TITLE
Can you generate new rubygem version please?

### ISSUE THREAD

**Issue by rhulse** [soulim/oembed#7]

**Comment by soulim** [comment]
@rhulse yes, sure. Will build a new gem ASAP.

**Comment by rhulse** [comment]
Thanks! I appreciate the quick reply. I wanted to pick up the patch that @rossjourdain submitted (he was working for us at the time). :-)

**Comment by soulim** [comment]
@rhulse you could get [v0.2.0](https://rubygems.org/gems/oembed/versions/0.2.0) from rubygems.org.

**Comment by soulim** [comment]
@rhulse I'll close the issue for now, but fill free to re-open it if something is wrong.

Wish you a wonderful day! 😄
